### PR TITLE
Exposing borderRadius and padding of popup for external use

### PR DESCRIPTION
**Pull request by lekanbar**
Hello,

I really like this library and thank you for creating it, found it useful among others that I tried, cos this is just simple.

However, I'd like to make a little contribution, which was borne out of a need. This contribution only exposes the `borderRadius` and `padding`, nothing much.

With those properties exposed, users of the library can then easily have full control of how the UI is drawn.

I will appreciate if the request is granted for everyone's benefit, thank you!

### CODE REVIEW

**Comment by snj07** [comment]
I am glad you found it useful. Thanks for the PR. It looks fine. I'll merge it.

**Comment by lekanbar** [comment]
Thank you! @snj07 

If I may ask, how soon will the library on pub.dev get this update?

**Comment by snj07** [comment]
I just published the changes and it should reflect on pub.dev soon.

**Comment by lekanbar** [comment]
Great!

**Pull request merged**
